### ISSUE TITLE
请问有没有测试代码

### ISSUE THREAD

**Issue by Lipolan** [csbhr/FFHQ-UV#20]
您好，我想请问一下这个项目可以测试自己的图片吗？就是用自己的照片，生产UV，拟合到shape中或者mesh中。还有一个就是可以获得最终的.obj文件吗？非常期待您的回复！

**Comment by csbhr** [comment]
你好，当想测试自己图片时，可以考虑使用 [RGB Fitting 代码](https://github.com/csbhr/FFHQ-UV#rgb-fitting) 来拟合 shape 和 texture，会同时得到 .obj 的 mesh 和 .png 的 texture UV-map。

**Comment by Lipolan** [comment]
感谢您的回答 ！！！我尝试跑您发的代码 ，但我好像有很多错误 。您有时间的话看一看我的环境，提一下意见与建议。感谢您！！！
服务器：
![服务器](https://user-images.githubusercontent.com/95124201/226556415-a4b089f5-f82f-446d-91ab-d5aa5f6669e9.png)
conda环境：
![image](https://user-images.githubusercontent.com/95124201/226556687-d6326802-1f86-4a19-ad2e-e03f662632fd.png)
![image](https://user-images.githubusercontent.com/95124201/226556774-969fd5b0-24ab-4d39-8ada-3d2c5e823386.png)
但是会报najia的错误

bash run_ffhq_uv_dataset.sh
[run_ffhq_uv_dataset.sh](https://github.com/csbhr/FFHQ-UV/blob/main/run_ffhq_uv_dataset.sh)
step1_process_data.py 这个py文件这样配置的
![image](https://user-images.githubusercontent.com/95124201/226557297-9fb2fd54-9c79-4a1e-a792-851e1988e31c.png)
会报如下的错误：
![image](https://user-images.githubusercontent.com/95124201/226557543-a8f4ceb3-1637-4d84-a796-1ec7de0342f7.png)

**Comment by slime898** [comment]
@Lipolan 
You can upgrade protobuf to 3.20 to solve by
`pip uninstall protobuf
pip install protobuf==3.20`

**Comment by Lipolan** [comment]
> @Lipolan You can upgrade protobuf to 3.20 to solve by `pip uninstall protobuf pip install protobuf==3.20`

Thank you very much. I have already solved this problem.

**Comment by pyh007** [comment]
作者你好，请问下报这个错什么原因：
/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/site-packages/requests/__init__.py:114: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (None)/charset_normalizer (3.1.0) doesn't match a supported version!
  RequestsDependencyWarning,
Traceback (most recent call last):
  File "run_e4e_inversion.py", line 10, in <module>
    from models.psp import pSp  # we use the pSp framework to load the e4e encoder.
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/psp.py", line 6, in <module>
    from models.encoders import psp_encoders
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/encoders/psp_encoders.py", line 9, in <module>
    from models.stylegan2.model import EqualLinear
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/stylegan2/model.py", line 7, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/stylegan2/op/fused_act.py", line 6, in <module>
    from torch.utils.cpp_extension import load
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
    from .hipify import hipify_python
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
    from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
    rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
我是nvidia的gpu为什么会用这个来编译
