### ISSUE TITLE
Generation process in `run_rgb_fitting.sh` vs `run_ffhq_uv_dataset.sh`

### ISSUE THREAD

**Issue by akasharidas** [csbhr/FFHQ-UV#30]
I'm trying to generate a texture from a custom image. Is there any difference between these two options? 
1. Run `run_rgb_fitting.sh` on my image
2. Place my image into the dataset folder and run `run_ffhq_uv_dataset.sh` 

When testing both options using an FFHQ image, the texture generated by `run_rgb_fitting.sh` seems to be lower fidelity.

**Comment by pyh007** [comment]
你好，请问你部署环境的时候遇到这个问题了吗，
Traceback (most recent call last):
  File "run_e4e_inversion.py", line 10, in <module>
    from models.psp import pSp  # we use the pSp framework to load the e4e encoder.
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/psp.py", line 6, in <module>
    from models.encoders import psp_encoders
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/encoders/psp_encoders.py", line 9, in <module>
    from models.stylegan2.model import EqualLinear
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/stylegan2/model.py", line 7, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/akira/FFHQ-UV/DataSet_Step1_Inversion/models/stylegan2/op/fused_act.py", line 6, in <module>
    from torch.utils.cpp_extension import load
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
    from .hipify import hipify_python
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
    from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
    rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/akira/anaconda3/envs/ffhq-uv/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'

**Comment by csbhr** [comment]
Please see [here](https://github.com/csbhr/FFHQ-UV#generate-a-uv-texture-map-from-a-single-facial-image) for details.
