### ISSUE TITLE
Add eye ball to Mesh is not working !

### ISSUE THREAD

**Issue by NaToh5** [csbhr/FFHQ-UV#41]
Hello, I have a problem when I run mesh_add_eyeball.py, it just creates the two eyeball but it is not applied to the mesh head, so the final mesh head obj is still blank !

**Comment by csbhr** [comment]
The main aim of the "run mesh_add_eyeball.py" script is to adjust the size and position of the eye meshes, so that they can match the head mesh well. This script does not add the eye meshes to the head mesh, but outputs two .obj files (two eyeball meshes). 

When rendering (or when previewing in MeshLab), three .obj files (head mesh and two eyeball meshes) need to be loaded at the same time.

**Comment by NaToh5** [comment]
Could you give me some tips to apply the eyeball into head mesh with python code ? or it can only done with 3D modeling tools?

Thanks.

**Comment by csbhr** [comment]
Maybe, you need to merge the vertices together in the .obj file, and then update the corresponding indices. But this may cause problems when reading eyeball textures, because one .obj file cannot correspond to multiple UV texture maps.

So, I don't recommend merging them into one .obj file. It is more reasonable to process them separately with 3D modeling tools.

**Comment by NaToh5** [comment]
Thank you for your kind reply. Could you also help me to sovle this problem in Step 3 Editing phase ? 

```
Traceback (most recent call last):
  File "run_styleflow_editing.py", line 318, in <module>
    sf_model = StyleFlow(args)
  File "run_styleflow_editing.py", line 69, in __init__
    self.stylegan_model = Build_model(args)
  File "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\utils.py", line 192, in __init__
    _G, _D, Gs = pretrained_networks.load_networks(network_pkl)
  File "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\pretrained_networks.py", line 114, in load_networks
    G, D, Gs = pickle.load(stream, encoding='latin1')
  File "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\dnnlib\tflib\network.py", line 297, in __setstate__
    self._init_graph()
  File "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\dnnlib\tflib\network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 491, in G_synthesis_stylegan2
  File "<string>", line 455, in layer
  File "<string>", line 99, in modulated_conv2d_layer
  File "<string>", line 68, in apply_bias_act
  File "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\dnnlib\tflib\ops\fused_bias_act.py", line 68, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\dnnlib\tflib\ops\fused_bias_act.py", line 122, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\dnnlib\tflib\ops\fused_bias_act.py", line 16, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\dnnlib\tflib\custom_ops.py", line 131, in get_plugin
    _run_cmd(_prepare_nvcc_cli('"%s" --preprocess -o "%s" --keep --keep-dir "%s"' % (cuda_file, tmp_file, tmp_dir)))
  File "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\dnnlib\tflib\custom_ops.py", line 71, in _run_cmd
    raise RuntimeError('NVCC returned an error. See below for full command line and output log:\n\n%s\n\n%s' % (cmd, output))
RuntimeError: NVCC returned an error. See below for full command line and output log:

nvcc "C:\Users\ADMIN\Desktop\ffhq\DataSet_Step3_Editing\dnnlib\tflib\ops\fused_bias_act.cu" --preprocess -o "C:\Users\ADMIN\AppData\Local\Temp\tmp6e_uuczb\fused_bias_act_tmp.cu" --keep --keep-dir "C:\Users\ADMIN\AppData\Local\Temp\tmp6e_uuczb" --disable-warnings --include-path "C:\Users\ADMIN\anaconda3\envs\RGB\lib\site-packages\tensorflow_core\include" --include-path "C:\Users\ADMIN\anaconda3\envs\RGB\lib\site-packages\tensorflow_core\include\external\protobuf_archive\src" --include-path "C:\Users\ADMIN\anaconda3\envs\RGB\lib\site-packages\tensorflow_core\include\external\com_google_absl" --include-path "C:\Users\ADMIN\anaconda3\envs\RGB\lib\site-packages\tensorflow_core\include\external\eigen_archive" --compiler-bindir "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64" 2>&1

fused_bias_act.cu
C:/Users/ADMIN/Desktop/ffhq/DataSet_Step3_Editing/dnnlib/tflib/ops/fused_bias_act.cu(9): fatal error C1083: Cannot open include file: 'tensorflow/core/framework/op.h': No such file or directory
```

**Comment by NaToh5** [comment]
Thank you @csbhr . Look like I have to find another PC that can run cuda version 10.

**Comment by tomyjack** [comment]
> Thank you @csbhr . Look like I have to find another PC that can run cuda version 10.
use nvidia-tensorflow just well for you
