### ISSUE TITLE
about install pytorch3d match python version

### ISSUE THREAD

**Issue by zw20045500** [csbhr/FFHQ-UV#42]
Hello,Thanks for the great work. 

Installation requirement
Python 3.7
git clone https://github.com/facebookresearch/pytorch3d

but pytorch3d github Installation is :
<img width="1067" alt="image" src="https://github.com/csbhr/FFHQ-UV/assets/30209916/b964853f-2576-4141-b627-e337f36a6d4f">
it require Python 3.8, 3.9 or 3.10
how to do it?

when install pytorch3d failed, the error part message is like 
ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/migu/anaconda3/envs/ffhq-uv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
        env=env)
      File "/home/migu/anaconda3/envs/ffhq-uv/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception
Can you give me some suggestion,Thanks in advance

**Comment by slime898** [comment]
Try to install old version of pytorch3d with corresponding packages.
You can find it from release issue of pytorch3d github.

**Comment by ashj9** [comment]
Hey @slime898, could you please mention about the older version of pytorch3d that you are referring to?

TIA

**Comment by csbhr** [comment]
Maybe you can try `git clone -b v0.6.2 https://github.com/facebookresearch/pytorch3d`.

This version supports Python 3.7 and PyTorch 1.7
<img width="522" alt="image" src="https://github.com/csbhr/FFHQ-UV/assets/26042636/612abe78-7ac8-4847-965b-6d7a243cb10b">
